version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "firstlambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gff95rp69xrg"
s3_prefix = "firstlambda"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
